microservicio: 
  id: 01
  nombre: micro1

acciones:

  # -------------------------
  # PERSONAS
  # -------------------------

  - personas
  - personas.crear
  - personas.leer
  - personas.actualizar
  - personas.eliminar
  - medico
  - medico.crear
  - medico.leer
  - medico.actualizar
  - medico.eliminar

  # -------------------------
  # PLANES
  # -------------------------

  - planes
  - planes.crear
  - planes.leer
  - planes.actualizar
  - planes.eliminar

  # -------------------------
  # CONFIG
  # -------------------------

  - sedes
  - sedes.crear
  - sedes.leer
  - sedes.actualizar
  - sedes.eliminar
  - tiposdocumento
  - tiposdocumento.crear
  - tiposdocumento.leer
  - tiposdocumento.actualizar
  - tiposdocumento.eliminar
  - tipossede
  - tipossede.crear
  - tipossede.leer
  - tipossede.actualizar
  - tipossede.eliminar
  - aulas
  - aulas.crear
  - aulas.leer
  - aulas.actualizar
  - aulas.eliminar
  - rangos
  - rangos.crear
  - rangos.leer
  - rangos.actualizar
  - rangos.eliminar

  # -------------------------
  # ASIGNATURAS
  # -------------------------

  - asignaturas
  - asignaturas.crear
  - asignaturas.leer
  - asignaturas.actualizar
  - asignaturas.eliminar

  # -------------------------
  # COMISIONES
  # -------------------------

  - comisiones
  - comisiones.crear
  - comisiones.leer
  - comisiones.actualizar
  - comisiones.eliminar

roles:
  nombre: admin
    acciones:
      - *
  nombre: gestionpersonas
    acciones:
      - personas
      - personas.crear
      - personas.leer
      - personas.actualizar
      - personas.eliminar
      - medico
      - medico.crear
      - medico.leer
      - medico.actualizar
      - medico.eliminar
  
