events { worker_connections 1024; }

http {
    server {
        listen 8000;

        #Aca hay que ver cual es el front que atiende primero
        location / {
            proxy_pass http://172.10.10.30:5173;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
        }

        #Hay que agregar el resto de los back. api/g2/ api/g3/
        location /api/g1/ {
            proxy_pass http://172.10.10.20:5000/; 
        }
    }
}