events { worker_connections 1024; }

http {
    server {
        listen 8000;

        # 1. Tu Frontend (React) sigue en la raíz
        location / {
            proxy_pass http://frontend:5173;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
        }

        # 2. TU prefijo de grupo (Grupo 1)
        # Nginx va a escuchar /api/g1/ y se lo va a mandar limpio a tu Flask
        location /api/g1/ {
            proxy_pass http://backend:5000/; # <-- Clave la barra / al final
        }
    }
}